//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace management_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUPON
    {
        public string CODE { get; set; }
        public Nullable<int> VALUE { get; set; }
        public Nullable<int> AVAILABLE { get; set; }
    }
}
