//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace management_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ORDER_ID { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> TOTAL { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
