//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace management_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public string PNAME { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> PSTATUS { get; set; }
        public string CATE { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
